name: CI

on:
- push
- pull_request

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1
    - name: Install apt dependencies
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y -qq grass grass-dev grass-doc
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Print version numbers
      run: |
        grass --version
        python3 --version
        python --version
    - name: Try interface of all the scripts with GRASS interface
      run: |
        for script in compute_cost.py compute_flow_columns.py create_visualization_helpers.py
        do
            grass --tmp-location XY --exec ./$script --help
        done
